#include "token.h"

std::unordered_map<TokenType, std::string> tokenTypeStrings {
    { TokenType::LBRACE,            "LBRACE",           },
    { TokenType::RBRACE,            "RBRACE",           },
    { TokenType::LPAREN,            "LPAREN",           },
    { TokenType::RPAREN,            "RPAREN",           },
    { TokenType::SEMICOLON,         "SEMICOLON",        },
    { TokenType::MINUS,             "MINUS",            },
    { TokenType::COMPLEMENT,        "COMPLEMENT",       },
    { TokenType::NEGATION,          "NEGATION",         },
    { TokenType::PLUS,              "PLUS",             },
    { TokenType::INCREMENT,         "INCREMENT",        },
    { TokenType::DECREMENT,         "DECREMENT",        },
    { TokenType::STAR,              "STAR",             },
    { TokenType::MODULO,            "MODULO",           },
    { TokenType::SLASH,             "SLASH",            },
    { TokenType::COLON,             "COLON",            },
    { TokenType::QUESTION_MARK,     "QUESTION_MARK",    },
    { TokenType::COMMA,             "COMMA",            },
    { TokenType::AND,               "AND",              },
    { TokenType::OR,                "OR",               },
    { TokenType::EQ,                "EQ",               },
    { TokenType::NEQ,               "NEQ",              },
    { TokenType::LT,                "LT",               },
    { TokenType::LE,                "LE",               },
    { TokenType::GT,                "GT",               },
    { TokenType::GE,                "GE",               },
    { TokenType::ASSIGN,            "ASSIGN",           },
    { TokenType::PLUS_ASSIGN,       "PLUS_ASSIGN",      },
    { TokenType::MINUS_ASSIGN,      "MINUS_ASSIGN",     },
    { TokenType::DIV_ASSIGN,        "DIV_ASSIGN",       },
    { TokenType::MULT_ASSIGN,       "MULT_ASSIGN",      },
    { TokenType::MOD_ASSIGN,        "MOD_ASSIGN",       },

    { TokenType::RETURN,            "RETURN",           },
    { TokenType::INT,               "INT",              },
    { TokenType::FOR,               "FOR",              },
    { TokenType::WHILE,             "WHILE",            },
    { TokenType::DO,                "DO",               },
    { TokenType::BREAK,             "BREAK",            },
    { TokenType::CONTINUE,          "CONTINUE",         },

    { TokenType::IDENTIFIER,        "IDENTIFIER",       },
    { TokenType::INTEGER_LITERAL,   "INTEGER_LITERAL",  },

    { TokenType::END_OF_FILE,       "END_OF_FILE",      },
    { TokenType::INVALID,           "INVALID",          },
};
